### ISSUE TITLE
App crashes when internet connection is lost

### ISSUE THREAD

**Issue by firefoxlover** [flathub/io.github.Bavarder.Bavarder#11]
Really great app!

I have a problem that in my shitty wifi it sometimes just loses connectivity.

Instead of having a ping test to the used AI server or something, it just freezes.

The app doesnt even crash, I need to manually force it to close via pkill e.g.

## Proposed solution
Integrate some kind of internet connectivity check, like pinging the AI server every 5 seconds. If its negative, cancel the current process and display a message.

**Comment by firefoxlover** [comment]
version 0.2.3

**Comment by 0xMRTT** [comment]
https://github.com/Bavarder/Bavarder/issues/28 moved to the repo.
