### ISSUE TITLE
Flatpak is borked after 0.2.4 update

### ISSUE THREAD

**Issue by x80486** [flathub/io.github.Bavarder.Bavarder#14]
I've been waiting a little bit to report this one. I thought it was going to be an issue for everyone, but looks like it's not.

After updating to version `0.2.4`, the application doesn't work anymore. It starts successfully, but nothing can be typed and/or pasted. I don't see any errors in the journal either.

## System Info

```shell
[x80486@uplink:~]$ flatpak --version 
Flatpak 1.15.4

[x80486@uplink:~]$ uname -a
Linux uplink 6.1.39-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 19 Jul 2023 17:58:31 +0000 x86_64 GNU/Linux

[x80486@uplink:~]$ flatpak info io.github.Bavarder.Bavarder 
Bavarder - Chit-chat with an AI

          ID: io.github.Bavarder.Bavarder
         Ref: app/io.github.Bavarder.Bavarder/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.2.4
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 48.9 MB
     Runtime: org.gnome.Platform/x86_64/44
         Sdk: org.gnome.Sdk/x86_64/44

      Commit: 4af0e52d240e010ada53ba168a43b837d052980a0e6e341fc2fb3c4981419cb1
      Parent: 1cdb590835744d93f9c0b24de3c120ab94cc27f3e1528cdfc5b121168c2300b8
     Subject: Update pypi-dependencies.json to handle multiple architectures (5ef8f596)
        Date: 2023-07-23 22:41:21 +0000
```

**Comment by gcqmkm02** [comment]
Je confirme. J'ai le même souci.
Installé aujourd'hui de flathub et je suis sous ubuntu 23.10. 


bavarder:2): Gtk-CRITICAL **: 18:44:44.305: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed


J'ai essaiye de installer avec le flatpak-builder comme écrit sur le site web. Et ça me donne le error: org.gnome.Sdk/x86_64/master not installed

Thank you

**Comment by x80486** [comment]
> Je confirme. J'ai le même souci. Installé aujourd'hui de flathub et je suis sous ubuntu 23.10.
> 
> bavarder:2): Gtk-CRITICAL **: 18:44:44.305: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
> 
> J'ai essaiye de installer avec le flatpak-builder comme écrit sur le site web. Et ça me donne le error: org.gnome.Sdk/x86_64/master not installed
> 
> Thank you

If you ask me, I would guess that's french...but I have no idea what you just said there.

**Comment by 0xMRTT** [comment]
> Je confirme. J'ai le même souci. Installé aujourd'hui de flathub et je suis sous ubuntu 23.10.
> 
> bavarder:2): Gtk-CRITICAL **: 18:44:44.305: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
> 
> J'ai essaiye de installer avec le flatpak-builder comme écrit sur le site web. Et ça me donne le error: org.gnome.Sdk/x86_64/master not installed
> 
> Gnome-shell 44.3 python 3.11.4 $>flatpak info แบบวาร์เดอร์ - Chit-chat with an AI
> 
> 标识： io.github.Bavarder.Bavarder 引用： app/io.github.Bavarder.Bavarder/x86_64/stable 架构： x86_64 分支： stable 版本： 0.2.4 许可证： GPL-3.0-or-later 来源： flathub 集合： org.flathub.Stable 安装： system 已安装： 48,9 MB 运行时： org.gnome.Platform/x86_64/44 SDK： org.gnome.Sdk/x86_64/44
> 
> 交付： 4af0e52d240e010ada53ba168a43b837d052980a0e6e341fc2fb3c4981419cb1 上级： 1cdb590835744d93f9c0b24de3c120ab94cc27f3e1528cdfc5b121168c2300b8 主题： Update pypi-dependencies.json to handle multiple architectures ([5ef8f59](https://github.com/flathub/io.github.Bavarder.Bavarder/commit/5ef8f596c2268d081b1a13d4cc1be9825a6d1d39)) 日期： 2023-07-23 22:41:21 +0000
> 
> Est-ce que il y a un souci avec un paquet python? Thank you

Hello, I don't know what's happening with the flatpak package but it will be fixed soon in the next release.

**Comment by x80486** [comment]
This is fixed, but the application is somewhat buggy, in the sense that it restarts itself very continuously, as if it's doing some heavy background task(s).
