### ISSUE TITLE
App crashes when I click on send button

### ISSUE THREAD

**Issue by SROG33** [flathub/io.github.Bavarder.Bavarder#4]
I am using as flatpak on Alpine Linux.
Error log:
@a{ss} {}
['baichat', 'catgpt', 'huggingchat', 'openaigpt35turbo', 'openaigpt4']
Loading provider baichat
Provider baichat  -> KeyError, skipping...
Loading provider catgpt
Provider catgpt  -> KeyError, skipping...
Loading provider huggingchat
Provider huggingchat  -> KeyError, skipping...
Loading provider openaigpt35turbo
Provider openaigpt35turbo  -> KeyError, skipping...
Loading provider openaigpt4
Provider openaigpt4  -> KeyError, skipping...
huggingchat
Setting selected provider to 2
**
Gtk:ERROR:../gtk/gtktextview.c:4764:gtk_text_view_validate_onscreen: assertion failed: (priv->onscreen_validated)
Bail out! Gtk:ERROR:../gtk/gtktextview.c:4764:gtk_text_view_validate_onscreen: assertion failed: (priv->onscreen_validated)
Aborted

**Comment by 0xMRTT** [comment]
https://github.com/Bavarder/Bavarder/issues/19

**Comment by 0xMRTT** [comment]
Fixed in 0.1.6
